### ISSUE TITLE
Data set related issues

### ISSUE THREAD

**Issue by yunchao-ding** [changwoonchoi/IBL-NeRF#1]
Hi,
What should I fill in after the ”dataset_type =  “ equation in this ”configs/IBL-NeRF/common.txt“ document?
If I want to train pictures of the kitchen.
There seems to be no "/config/IBL-NeRF/kitchen.txt" file in your file.
Thank you again for your excellent work!

**Comment by changwoonchoi** [comment]
Thank you for your reporting.

Since we support the "mitsuba" dataset type only in the current version, the dataset_type should be mitsuba.

I fixed the default value of config_parser.py and the corresponding config file anyway! :)

**Comment by yunchao-ding** [comment]
Thank you for your suggestions and help!
