### ISSUE TITLE
Object Insertion Problem

### ISSUE THREAD

**Issue by XinLyu1** [changwoonchoi/IBL-NeRF#13]
Hi, 
Thanks for your great work! In object insertion, how to produce object_insert_mask, object_insert_normal and object_insert_depth image? I don't find any instructions in README.

**Comment by changwoonchoi** [comment]
Hi,
For the applications of IBL-NeRF, namely object insertion and intrinsic component editing, we did not provide the example files.
But you can freely make your own file to edit the scene.
Basically, all you have to do is making pixel-wise masks, and values to override the trained scene.
For example, if you want to modify the roughness value of the table, you need to create the mask of the table region and the roughness values you want to edit.
Or, if you want to insert the objects, you can create the depth, normal, mask image of the target inserting objects and override with it.
