### ISSUE TITLE
How to get the prefiltered radiance with python?

### ISSUE THREAD

**Issue by BlueSky-Lillia** [changwoonchoi/IBL-NeRF#14]
I notice that your dataset contain the prefiltered radiance, I am a green hand in CG and I do not know more about C++, so I have a great interest and  want to learn how to use python to generate prefiltered radiance. Sincerely hope that you can help me with this question

**Comment by changwoonchoi** [comment]
Hi, what do you mean our dataset contain prefiltered radiance? We are training prefiltered radiance fields while reconstructing the other components.
