### ISSUE TITLE
Error occurred when saving "irradiance_map"?

### ISSUE THREAD

**Issue by SleepEaaarly** [changwoonchoi/IBL-NeRF#15]
Hello it's great work and dataset you've made. I am trying to run your code with your dataset "bathroom". However an error occurred like below.
![image](https://github.com/user-attachments/assets/63dee64a-4288-4461-bf7a-815134f66b0f)
The version of python is 3.10 and pytorch was installed using instruction "pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu121".(Because a CUDA Error occurred, when i use python with 3.8 and pytorch you recommended.) Our packages were installed by "requirements.txt". How can I fix this error quickly?
By the way, in your google driver i only found synthetic dataset you mentioned in your paper but no dataset of real scenes. How could i find them? Or when to release them?

**Comment by changwoonchoi** [comment]
Hi, I think it came from the version difference on pillow library.
You can just duplicate channels to make them 3 (R, G, B) and save 3-channel image or install previous version of pillow to save single-channel image.

**Comment by changwoonchoi** [comment]
For real-world dataset, there is no plan to release them, apologize for it🙏
