### ISSUE TITLE
"Load BRDF LUT"

### ISSUE THREAD

**Issue by yunchao-ding** [changwoonchoi/IBL-NeRF#2]
Hi,
Dear author, I encountered a problem with the data set during the experiment, "brdf_lut_path="../data/ibl_brdf_lut. png "". Is there any lack of corresponding "ibl_brdf_lut. png" images?
Yously.

**Comment by changwoonchoi** [comment]
Hi,
The BRDR LUT image was missing from the google drive link.
I uploaded the BRDF LUT image to this GitHub repository!

**Comment by yunchao-ding** [comment]
Thank you very much for your help!
