### ISSUE TITLE
Problems encountered in output results

### ISSUE THREAD

**Issue by yunchao-ding** [changwoonchoi/IBL-NeRF#3]
Hi,
Dear author, I encountered several unsolvable problems in the process of running your open source code. I have collated them and sent them to your mailbox. I hope I can get your help.
Thank you again for your contribution.

**Comment by changwoonchoi** [comment]
Hi!
I wanted to check in and see if you had sent an email regarding the problems you mentioned.
I searched my inbox, but I couldn't find anything from you.

**Comment by yunchao-ding** [comment]
Sorry, I sent the wrong email due to my mistake. Please forgive my mistake. I have emailed you again. Thank you for your help.

**Comment by changwoonchoi** [comment]
Now I checked your email!

Please refer to it.

**Comment by yunchao-ding** [comment]
I have received your email. Thank you very much for your help!
