### ISSUE TITLE
The output image blur problem has not been resolved

### ISSUE THREAD

**Issue by yunchao-ding** [changwoonchoi/IBL-NeRF#4]
Hello,
Dear author, based on the problem that the output image was very blurred before, I have tried a lot, but I still can't solve the problem of the output image blur, and I can't achieve the clarity like your paper. Earlier you asked me to check the 'render_factor' parameter and render the output at full resolution, but it seems that I didn't manage to solve this problem, hope to get your help again.

I have another question for you:
Is it possible to obtain images from all angles when a few images from different angles are known, as in nerf? Can your experimental results also obtain results for all light intensities (or albedo) with a small number of light intensities? For example, when the light intensity (or albedo) is known to be [0, 0.5, 0.8, 1.0] these four values, can you synthesize an image with the light intensity value in the middle, such as [0.25, 0.6, 0.9]? Image?
Thank you so much!

**Comment by changwoonchoi** [comment]
Hi,
1) Regarding the blurry output issue
> Can you tell me the dimension/resolution of your output images?

2) Is it possible to obtain images from all angles when a few images from different angles are known, as in nerf?
> I'm uncertain if I comprehended your inquiry completely. As IBL-NeRF is a NeRF-based approach, it is able to generate novel view images given a training dataset of muli-view images.

3) Can your experimental results also obtain results for all light intensities (or albedo) with a small number of light intensities?
> Of course. If you override the any of the intrinsic components, you can obtain edited images.

**Comment by yunchao-ding** [comment]
1. Without modifying the open source code you released at all, the resolution of the input image dataset is 640×360, but the resolution of the output image is only 160×90.
2. For the new view synthesis problem of nerf, what I want to express is the multi-view new view generated by nerf. Can the variable "multi-view" be replaced with "multi-light intensity"? Is it possible to only generate a new view angle image, but not a new light intensity image?
Thank you so much!

**Comment by changwoonchoi** [comment]
1. As I said before, you can obtain the full-resolution image by modifying the "render_factor" option. However, I pushed a new commit that modifies hardcoded render_factor to a configurable parameter anyway. Now you can obtain full-resolution images by running the default config file. (I updated the default config file too.)
2. If a user supplies the new light intensity, the output would be changed accordingly.

**Comment by yunchao-ding** [comment]
Thank you very much for your help and sorry for taking up your precious time.

**Comment by changwoonchoi** [comment]
No problem :)
