### ISSUE TITLE
Scene editing problems, such as roughness and albedo modification

### ISSUE THREAD

**Issue by yunchao-ding** [changwoonchoi/IBL-NeRF#5]
Hi,
Dear author, sorry to bother you, I have some questions during the training process and would like to ask you for advice. I saw in your thesis that there is a function to edit the scene. That is, after IBL-NeRF decomposes the intrinsic components, a realistic new view image of the changed scene can be rendered by modifying the value of each component. How to modify to achieve the content shown in Figure 9 in the paper? Such as modifying roughness, albedo, etc. The output image is not changed in angle, but the values such as roughness and albedo in the image are changed, such as the results shown in Figure 9 and Figure 19.
Thank you for your help!

**Comment by changwoonchoi** [comment]
Hi,
To edit a scene or insert known 3D objects inside the scene, you can simply override the `target_{}_map`s inside the `raw2outputs` function of `ibl_nerf_renderer.py` into your new intrinsic components to replace at the specific viewpoint.

**Comment by yunchao-ding** [comment]
Thank you very much for your help!
