### ISSUE TITLE
BRDF_LUT image generate

### ISSUE THREAD

**Issue by XiaoKangW** [changwoonchoi/IBL-NeRF#6]
Hi, Changwoon,

Thanks for you update the repository!
 I find there was the BRDF LUT image in data folder,  so i want to ask how to generate the the BRDF LUT image,  and this image is just used for kitchen dataset or all dataset.

Thanks!

**Comment by changwoonchoi** [comment]
Hi, thank you for your interest in our work.

BRDF LUT image is the BRDF integration map which stores scale and bias value to the surface's Fresnel response.
Thus, the LUT image is identical across all scenes.

The detailed explanation regarding the LUT can be found on the following website. Please refer to it.
https://learnopengl.com/PBR/IBL/Specular-IBL
