### ISSUE TITLE
 4.2. Scene Editing

### ISSUE THREAD

**Issue by Pomelo-king** [changwoonchoi/IBL-NeRF#8]
Hi,
Regarding the 4.2 Scene Editing part in your thesis, I failed to understand the principle here. For example, in the third line in Figure 9, in a real scene, how to modify only the albedo and roughness of the table mat to achieve the editing effect, and have no effect on other objects in the image except the table mat? The editing rationale here does not seem to be specifically stated in your paper. It just shows that after decomposing the intrinsic components, it can be rendered by modifying the value of each component.

Since the data set you disclosed does not contain a real-world scene data set, if I only want to edit the albedo and roughness of the wall behind the green kettle in the kitchen data image, so that it cannot produce reflections, and it will affect other images in the image The object is not edited (similar to the real scene in Figure 9 in the paper, only the desktop pad is edited, but other objects are not edited). Since there is no code related to this scene editing in your public code, can you give a specific code example with this example?

**Comment by yunchao-ding** [comment]
Hi,
I also have this doubt. I want to ask the author about this question.

**Comment by changwoonchoi** [comment]
Hi,
We assume that a user gives additional input to modify the target scene. (e.g. 2D mask of editing object & corresponding intrinsic values.)
I'll add codes for editing scene components or inserting objects soon!

**Comment by Pomelo-king** [comment]
Hi,
I very much look forward to your work.

**Comment by xcandxc** [comment]
Hello author,
I am interested in your work - the combination of IBL and NERF. I also encountered a problem when running your code that I was unable to edit the scene.

**Comment by xcandxc** [comment]
@Pomelo-king 
Hi,Has the author uploaded the added scenario editing code yet?

**Comment by changwoonchoi** [comment]
Hi,
I uploaded sample codes for editing scenes.
(I haven't uploaded 2D masks for editing scenes. You can freely create a 2D mask and edit it as you wish.)

**Comment by xcandxc** [comment]
Hi,
Thank you very much for your work!





繁华似梦
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "changwoonchoi/IBL-NeRF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月20日(星期一) 晚上8:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [changwoonchoi/IBL-NeRF]  4.2. Scene Editing (Issue #8)





 
Hi,
 I uploaded sample codes for editing scenes.
 (I haven't uploaded 2D masks for editing scenes. You can freely create a 2D mask and edit it as you wish.)
